### PR TITLE
Fix regex string and add .gitignore

### PR DESCRIPTION
**Pull request by thawatchai**
* fix regex string error
* reformat Python code
* add .gitignore

### CODE REVIEW

**Review by yodiaditya — CHANGES_REQUESTED** [review]
@thawatchai could you please remove the .gitignore in the commit?

**Comment by thawatchai** [comment]
> @thawatchai could you please remove the .gitignore in the commit?

I thought you have missed `.gitignore`. Now, I know that it's your intention to exclude it. I'm wondering why don't you want to have `.gitignore` in the repo? 🤔

**Comment by yodiaditya** [comment]
> > @thawatchai could you please remove the .gitignore in the commit?
> 
> I thought you have missed `.gitignore`. Now, I know that it's your intention to exclude it. I'm wondering why don't you want to have `.gitignore` in the repo? 🤔

Everyone has different environment, IDE, etc

**Comment by yodiaditya** [comment]
Thank you for your contribution @thawatchai !

**Pull request merged**
